name: Pylint & Flake8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Installation des dependances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint hypothesis flake8 flake8-docstrings
    - name: Analyse du code par pylint
      run: |
        pylint `find $PWD|grep .py$|xargs`
    - name: Analysing the code par flake8
      run: |
        flake8 --ignore D401,W503 \
        --per-file-ignores='setup.py:D100 main.py:D100 rollnjump/__init__.py:D104' \
        `find $PWD|grep .py$|xargs`
